# Generated by Django 2.2.5 on 2019-10-14 07:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hosts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('id_client', models.IntegerField()),
                ('hostname', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(choices=[('Fortigate', 'Fortigate'), ('Cisco', 'Cisco'), ('Juniper', 'Juniper'), ('Huawei', 'Huawei'), ('Raisecom', 'Raisecom'), ('Other', 'Other / No backup')], max_length=50)),
                ('is_monitored', models.BooleanField(default=True)),
                ('is_logged', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hosts',
            },
        ),
        migrations.CreateModel(
            name='Logged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_saves', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('ssh_username', models.CharField(max_length=50)),
                ('ssh_password', models.CharField(max_length=50)),
                ('status', models.CharField(default='OK', max_length=500)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
            ],
            options={
                'verbose_name_plural': 'Logged',
            },
        ),
        migrations.CreateModel(
            name='Monitored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_saves', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('current_state', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], default='UP', max_length=4)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_notification', models.BooleanField(default=False)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
            ],
            options={
                'verbose_name_plural': 'Monitored',
            },
        ),
        migrations.CreateModel(
            name='MonitoredHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], default='UP', max_length=4)),
                ('monitored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Monitored')),
            ],
            options={
                'verbose_name_plural': 'Monitored History',
            },
        ),
        migrations.CreateModel(
            name='LoggedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('filelink', models.FileField(upload_to=hosts.models.file_path)),
                ('logged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Logged')),
            ],
            options={
                'verbose_name_plural': 'Logged History',
            },
        ),
    ]
